name: 'PR Label Force Validator'
author: 'Sczlog'
description: 'Check if the PR has valid labels'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  github-token:
    description: 'The GitHub token'
    required: true
  valid-labels:
    description: 'List of valid labels'
    required: true
  invalid-labels:
    description: 'List of invalid labels'
    required: false
    default: ''
  pull-request-number:
    description: 'The Pull Request number'
    required: false
  disable-reviews:
    description: 'Should the action post reviews on PRs'
    required: false
  image:
    description: 'The image to use'
    required: false
    default: 'Dockerfile'
runs:
  using: 'docker'
  image: '${{ inputs.image }}'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.valid-labels }}
    - ${{ inputs.invalid-labels }}
    - ${{ inputs.pull-request-number }}
    - ${{ inputs.disable-reviews }}
